services:
  php:
    container_name: sylius-standard-php
    build:
      context: .
      target: sylius_php_prod
    image: olihock/sylius-standard-php:1.12
    depends_on:
      - migrations
    environment:
      APP_DEBUG: 0
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET:?APP_SECRET must be set}
      DATABASE_URL: mysql://sylius:${MYSQL_PASSWORD}@sylius-standard-mysql/sylius_prod
      MAILER_URL: gmail+smtp://oliver.hock@ithoc.de:${MAILER_PASSWORD}@default
      MESSENGER_TRANSPORT_DSN: doctrine://default
      SYLIUS_MESSENGER_TRANSPORT_MAIN_DSN: doctrine://default
      SYLIUS_MESSENGER_TRANSPORT_MAIN_FAILED_DSN: doctrine://default?queue_name=main_failed
      SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_DSN: doctrine://default?queue_name=catalog_promotion_removal
      SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_FAILED_DSN: doctrine://default?queue_name=catalog_promotion_removal_failed
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    volumes:
      # use a bind-mounted host directory, as we want to keep the sessions
      - ./var/sessions:/srv/sylius/var/sessions:rw
      # use a bind-mounted host directory, as we want to keep the media
      - ./public/media:/srv/sylius/public/media:rw
    networks:
      - sylius

  cron:
    container_name: sylius-standard-cron
    build:
      context: .
      target: sylius_cron
    image: olihock/sylius-standard-cron:1.12
    depends_on:
      - migrations
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ${APP_SECRET:?APP_SECRET must be set}
      DATABASE_URL: mysql://sylius:${MYSQL_PASSWORD}@sylius-standard-mysql/sylius_prod
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    networks:
      - sylius

  worker:
    container_name: sylius-standard-worker
    command: ["php", "bin/console", "messenger:consume", "main", "catalog_promotion_removal", "--limit=5", "--memory-limit=256M", "--time-limit=600"]
    restart: always
    build:
      context: .
      target: sylius_php_prod
    image: olihock/sylius-standard-worker:1.12
    depends_on:
      - migrations
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ${APP_SECRET:?APP_SECRET must be set}
      DATABASE_URL: mysql://sylius:${MYSQL_PASSWORD}@sylius-standard-mysql/sylius_prod
      MESSENGER_TRANSPORT_DSN: doctrine://default
      SYLIUS_MESSENGER_TRANSPORT_MAIN_DSN: doctrine://default
      SYLIUS_MESSENGER_TRANSPORT_MAIN_FAILED_DSN: doctrine://default?queue_name=main_failed
      SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_DSN: doctrine://default?queue_name=catalog_promotion_removal
      SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_FAILED_DSN: doctrine://default?queue_name=catalog_promotion_removal_failed
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    networks:
      - sylius

  migrations:
    container_name: sylius-standard-migrations
    build:
      context: .
      target: sylius_migrations_prod
    image: olihock/sylius-standard-migrations:1.12
    depends_on:
      - mysql
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ${APP_SECRET:?APP_SECRET must be set}
      DATABASE_URL: mysql://sylius:${MYSQL_PASSWORD}@sylius-standard-mysql/sylius_prod
      LOAD_FIXTURES: ${LOAD_FIXTURES:-0}
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    networks:
      - sylius

  mysql:
    container_name: sylius-standard-mysql
    # in production, we may want to use a managed database service
    image: mysql:5.7 # Sylius is fully working on mysql 8.0 version
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: sylius_prod
      MYSQL_USER: sylius
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set or empty}
    volumes:
      # use a bind-mounted host directory, because we never want to lose our data!
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - sylius

  nginx:
    container_name: sylius-standard-nginx
    # in production, we may want to use a static website hosting service
    build:
      context: .
      target: sylius_nginx
    image: olihock/sylius-standard-nginx:1.12
    depends_on:
      - php
    volumes:
      # use a bind-mounted host directory, as we want to keep the media
      - ./public/media:/srv/sylius/public/media:ro
    networks:
      - sylius
    ports:
      - "${NGINX_PORT:?NGINX_PORT must be set}:80"

networks:
  sylius:
    driver: bridge
